# Generated by Django 4.2.28 on 2026-02-21 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_contact_trading_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(db_index=True, help_text='Número CNJ do processo (formato: 1234567-89.2021.8.26.0100)', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Formato CNJ inválido. Use: 0000000-00.0000.0.00.0000', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$')])),
                ('numero_processo_unformatted', models.CharField(db_index=True, help_text='Número limpo (apenas dígitos) para busca', max_length=20)),
                ('titulo', models.CharField(blank=True, help_text='Título/Descrição resumida (ex: Ação de Cobrança - João Silva)', max_length=200)),
                ('tribunal', models.CharField(db_index=True, help_text='Ex: TJSP, TRF3, TST', max_length=10)),
                ('comarca', models.CharField(blank=True, help_text='Comarca/Subseção judiciária', max_length=100)),
                ('vara', models.CharField(blank=True, help_text='Vara/Turma/Câmara', max_length=200)),
                ('tipo_acao', models.CharField(blank=True, choices=[('CIVEL', 'Cível'), ('CRIMINAL', 'Criminal'), ('TRABALHISTA', 'Trabalhista'), ('TRIBUTARIA', 'Tributária'), ('FAMILIA', 'Família'), ('CONSUMIDOR', 'Consumidor'), ('OUTROS', 'Outros')], help_text='Área do direito', max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado'), ('ENCERRADO', 'Encerrado')], db_index=True, default='ATIVO', help_text='Status atual do processo', max_length=20)),
                ('auto_status', models.BooleanField(default=True, help_text='Se True, status é calculado automaticamente baseado em atividade')),
                ('data_distribuicao', models.DateField(blank=True, help_text='Data de distribuição/protocolo', null=True)),
                ('data_ultima_movimentacao', models.DateField(blank=True, db_index=True, help_text='Data da última publicação/movimentação (auto-atualizado)', null=True)),
                ('data_encerramento', models.DateField(blank=True, help_text='Data de encerramento/arquivamento', null=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da causa em R$', max_digits=15, null=True)),
                ('parte_contraria', models.CharField(blank=True, help_text='Nome da parte contrária (ré/autor/reclamada)', max_length=200)),
                ('observacoes', models.TextField(blank=True, help_text='Observações internas sobre o caso')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorização (ex: ["urgente", "aposentadoria"])')),
                ('deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete para auditoria')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_ultima_movimentacao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENTE', 'Cliente/Representado'), ('AUTOR', 'Autor'), ('REU', 'Réu'), ('TESTEMUNHA', 'Testemunha'), ('PERITO', 'Perito'), ('TERCEIRO', 'Terceiro Interessado')], default='CLIENTE', help_text='Papel da parte no processo', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a participação dessa parte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_roles', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
                'unique_together': {('case', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='clients',
            field=models.ManyToManyField(help_text='Clientes/partes envolvidas no processo', related_name='cases', through='cases.CaseParty', to='contacts.contact'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['tribunal', 'status'], name='cases_case_tribuna_225542_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-data_ultima_movimentacao'], name='cases_case_data_ul_2fc276_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['numero_processo_unformatted'], name='cases_case_numero__7ad4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['deleted', '-data_ultima_movimentacao'], name='cases_case_deleted_d374c8_idx'),
        ),
    ]
