# Generated by Django 4.2.28 on 2026-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parte_autora',
            field=models.CharField(blank=True, default='', help_text='Nome da parte autora (quem move a ação)', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='posicao_cliente',
            field=models.CharField(blank=True, choices=[('AUTOR', 'Autor (Cliente move a ação)'), ('REU', 'Réu (Cliente é processado)')], default='', help_text='Posição do cliente no processo', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='comarca',
            field=models.CharField(blank=True, default='', help_text='Comarca/Subseção judiciária', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Observações internas sobre o caso'),
        ),
        migrations.AlterField(
            model_name='case',
            name='parte_contraria',
            field=models.CharField(blank=True, default='', help_text='Nome da parte contrária (ré/autor/reclamada)', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='tipo_acao',
            field=models.CharField(blank=True, choices=[('CIVEL', 'Cível'), ('CRIMINAL', 'Criminal'), ('TRABALHISTA', 'Trabalhista'), ('TRIBUTARIA', 'Tributária'), ('FAMILIA', 'Família'), ('CONSUMIDOR', 'Consumidor'), ('OUTROS', 'Outros')], default='', help_text='Área do direito', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='vara',
            field=models.CharField(blank=True, default='', help_text='Vara/Turma/Câmara', max_length=200),
        ),
    ]
