# Generated by Django 4.2.28 on 2026-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparty',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Indica se este contato é o cliente do escritório neste processo'),
        ),
        migrations.AlterField(
            model_name='case',
            name='comarca',
            field=models.CharField(blank=True, default='', help_text='Comarca/Subseção judiciária', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Observações internas sobre o caso'),
        ),
        migrations.AlterField(
            model_name='case',
            name='parte_contraria',
            field=models.CharField(blank=True, default='', help_text='Nome da parte contrária (campo legado - usar CaseParty)', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='tipo_acao',
            field=models.CharField(blank=True, choices=[('CIVEL', 'Cível'), ('CRIMINAL', 'Criminal'), ('TRABALHISTA', 'Trabalhista'), ('TRIBUTARIA', 'Tributária'), ('FAMILIA', 'Família'), ('CONSUMIDOR', 'Consumidor'), ('OUTROS', 'Outros')], default='', help_text='Área do direito', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='vara',
            field=models.CharField(blank=True, default='', help_text='Vara/Turma/Câmara', max_length=200),
        ),
    ]
