# Generated by Django 4.2.28 on 2026-02-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_trading_name'),
        ('cases', '0002_caseparty_is_client_alter_case_comarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cliente_posicao',
            field=models.CharField(blank=True, choices=[('AUTOR', 'Autor/Requerente'), ('REU', 'Réu/Requerido')], default='', help_text='Posição do cliente principal no processo (opcional)', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='cliente_principal',
            field=models.ForeignKey(blank=True, help_text='Cliente principal deste processo (opcional - atalho para CaseParty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_como_cliente', to='contacts.contact'),
        ),
    ]
