# Generated by Django 4.2.28 on 2026-02-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_cliente_posicao_case_cliente_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='parte_contraria',
        ),
    ]
