# Generated by Django 4.2.28 on 2026-02-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_parte_contraria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, help_text='Data da movimentação/publicação')),
                ('tipo', models.CharField(choices=[('DESPACHO', 'Despacho'), ('DECISAO', 'Decisão Interlocutória'), ('SENTENCA', 'Sentença'), ('ACORDAO', 'Acórdão'), ('AUDIENCIA', 'Audiência'), ('JUNTADA', 'Juntada de Documento'), ('INTIMACAO', 'Intimação'), ('CITACAO', 'Citação'), ('CONCLUSAO', 'Conclusos'), ('RECURSO', 'Recurso'), ('PETICAO', 'Petição Protocolada'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', help_text='Tipo de movimentação', max_length=30)),
                ('titulo', models.CharField(help_text='Resumo breve da movimentação (ex: "Audiência de conciliação designada")', max_length=200)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição completa/observações detalhadas da movimentação')),
                ('prazo', models.IntegerField(blank=True, help_text='Prazo em dias (se aplicável)', null=True)),
                ('data_limite_prazo', models.DateField(blank=True, db_index=True, help_text='Data limite calculada (data + prazo)', null=True)),
                ('origem', models.CharField(choices=[('MANUAL', 'Cadastro Manual'), ('DJE', 'Importado do DJE'), ('ESAJ', 'Importado do e-SAJ'), ('PJE', 'Importado do PJE')], default='MANUAL', help_text='Origem/fonte da movimentação', max_length=20)),
                ('publicacao_id', models.IntegerField(blank=True, help_text='ID da publicação original (se veio de importação)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Processo ao qual esta movimentação pertence', on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='cases.case')),
            ],
            options={
                'verbose_name': 'Movimentação Processual',
                'verbose_name_plural': 'Movimentações Processuais',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['case', '-data'], name='cases_casem_case_id_304d5c_idx'), models.Index(fields=['-data'], name='cases_casem_data_a50938_idx'), models.Index(fields=['tipo', '-data'], name='cases_casem_tipo_efa163_idx')],
            },
        ),
    ]
