# Generated by Django 4.2.28 on 2026-02-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casemovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='observations_financial_block_a',
            field=models.TextField(blank=True, default='', help_text='Observações do bloco A (Valor do Processo)'),
        ),
        migrations.AddField(
            model_name='case',
            name='observations_financial_block_b',
            field=models.TextField(blank=True, default='', help_text='Observações do bloco B (Custos e Despesas)'),
        ),
        migrations.AddField(
            model_name='case',
            name='participation_fixed_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de participação do escritório (R$)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='participation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de participação do escritório (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='participation_type',
            field=models.CharField(choices=[('percentage', 'Percentual'), ('fixed', 'Valor Fixo')], default='percentage', help_text='Tipo de participação: percentual ou valor fixo', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_conditional',
            field=models.BooleanField(default=False, help_text='Cliente paga apenas mediante ganho de causa'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data do recebimento')),
                ('description', models.CharField(help_text='Descrição do recebimento (ex: Honorários - Parcela 1/3)', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor recebido em R$', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Processo relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cases.case')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['case', '-date'], name='cases_payme_case_id_d34a7f_idx'), models.Index(fields=['-date'], name='cases_payme_date_2a4d91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data da despesa')),
                ('description', models.CharField(help_text='Descrição da despesa (ex: Custas processuais, Honorários perito)', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor da despesa em R$', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Processo relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cases.case')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['case', '-date'], name='cases_expen_case_id_0ed13d_idx'), models.Index(fields=['-date'], name='cases_expen_date_394f37_idx')],
            },
        ),
    ]
