# Generated by Django 4.2.28 on 2026-02-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_observations_financial_block_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título curto da tarefa', max_length=255)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição detalhada da tarefa')),
                ('urgencia', models.CharField(choices=[('NORMAL', 'Prazo Normal'), ('URGENTE', 'Prazo Urgente'), ('URGENTISSIMO', 'Prazo Urgentíssimo')], db_index=True, default='NORMAL', help_text='Nível de urgência da tarefa', max_length=20)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, help_text='Data limite da tarefa (auto-calculada se não informada)', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', help_text='Status de execução da tarefa', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, help_text='Quando a tarefa foi concluída', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Processo relacionado à tarefa', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case')),
                ('movimentacao', models.ForeignKey(blank=True, help_text='Movimentação de origem (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.casemovement')),
            ],
            options={
                'verbose_name': 'Tarefa do Processo',
                'verbose_name_plural': 'Tarefas do Processo',
                'ordering': ['data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='cases_caset_case_id_bb22e4_idx'), models.Index(fields=['urgencia', 'data_vencimento'], name='cases_caset_urgenci_754776_idx'), models.Index(fields=['movimentacao'], name='cases_caset_movimen_fa35bf_idx')],
            },
        ),
    ]
