# Generated by Django 4.2.28 on 2026-02-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_publication_integra_59e9ce_idx'),
        ('cases', '0007_casetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='publicacao_origem',
            field=models.ForeignKey(blank=True, help_text='Publicação a partir da qual este caso foi criado (read-only, rastreabilidade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_criados', to='publications.publication'),
        ),
    ]
