# Generated by Django 4.2.28 on 2026-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_publicacao_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemovement',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca se o prazo foi resolvido/concluído'),
        ),
    ]
