# Generated by Django 4.2.28 on 2026-03-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_casemovement_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_dias', models.IntegerField(help_text='Número de dias do prazo (ex: 15, 30, 45)')),
                ('data_limite', models.DateField(db_index=True, help_text='Data limite calculada (data movimentação + prazo_dias)')),
                ('descricao', models.CharField(blank=True, default='', help_text='Descrição/motivo do prazo (ex: Manifestação, Recurso, Contrarrazões)', max_length=255)),
                ('completed', models.BooleanField(db_index=True, default=False, help_text='Se True, prazo foi concluído e sai do sistema de notificações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimentacao', models.ForeignKey(help_text='Movimentação que gerou este prazo', on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='cases.casemovement')),
            ],
            options={
                'verbose_name': 'Prazo Processual',
                'verbose_name_plural': 'Prazos Processuais',
                'ordering': ['data_limite'],
                'indexes': [models.Index(fields=['movimentacao', 'data_limite'], name='cases_casep_movimen_dcf6dc_idx'), models.Index(fields=['data_limite', 'completed'], name='cases_casep_data_li_f95b3c_idx')],
            },
        ),
    ]
