# Generated by Django 4.2.28 on 2026-03-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_case_participation_type_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Arquivo do documento', upload_to='case_documents/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, help_text='Nome original do arquivo enviado', max_length=255)),
                ('file_extension', models.CharField(blank=True, help_text='Extensão do arquivo (pdf, xls, xlsx, doc, docx)', max_length=10)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME do arquivo', max_length=120)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True)),
                ('tipo_documento', models.CharField(blank=True, default='', help_text='Categoria opcional (ex: petição, contrato, sentença)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descrição opcional do documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Processo relacionado ao documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'verbose_name': 'Documento do Processo',
                'verbose_name_plural': 'Documentos do Processo',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['case', '-uploaded_at'], name='cases_cased_case_id_7a1348_idx'), models.Index(fields=['file_extension'], name='cases_cased_file_ex_d79562_idx')],
            },
        ),
    ]
