# Generated by Django 4.2.28 on 2026-03-14 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0013_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsável pelo escopo deste processo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='numero_processo',
            field=models.CharField(db_index=True, help_text='Número CNJ do processo (formato: 1234567-89.2021.8.26.0100)', max_length=25, validators=[django.core.validators.RegexValidator(message='Formato CNJ inválido. Use: 0000000-00.0000.0.00.0000', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$')]),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner', 'deleted', '-data_ultima_movimentacao'], name='cases_case_owner_i_ed635e_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('owner', 'numero_processo'), name='unique_case_numero_per_owner'),
        ),
    ]
