# Generated by Django 4.2.28 on 2026-03-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('cases', '0014_case_owner_alter_case_numero_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização (tenant) deste processo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='organizations.organization'),
        ),
    ]
