# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_casetipoacaooption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTituloOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto exibido na lista', max_length=200)),
                ('key', models.CharField(db_index=True, help_text='Chave normalizada (sem acento, minúscula, espaços colapsados) para deduplicação', max_length=260, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_titulo_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção de Título do Processo',
                'verbose_name_plural': 'Opções de Título do Processo',
                'ordering': ['label'],
            },
        ),
    ]
