# Generated by GitHub Copilot

import unicodedata

from django.conf import settings
from django.db import migrations


def _normalize_key(value: str) -> str:
    raw = str(value or '').strip()
    if not raw:
        return ''
    nfd = unicodedata.normalize('NFD', raw)
    no_marks = ''.join(c for c in nfd if unicodedata.category(c) != 'Mn')
    collapsed = ' '.join(no_marks.split())
    return collapsed.lower()


TITULOS_SEED = [
    # Exemplos citados
    'Embargos à Execução Fiscal',
    'Execução - Cumprimento de Sentença',
    'Execução Contratual',
    'Execução de Pena',
    'Cobrança de Aluguéis - Sem Despejo',

    # Cível / Obrigações / Contratos
    'Ação de Cobrança',
    'Ação Monitória',
    'Execução de Título Extrajudicial',
    'Cumprimento de Sentença',
    'Ação de Indenização por Danos Morais',
    'Ação de Indenização por Danos Materiais',
    'Ação de Obrigação de Fazer',
    'Ação de Obrigação de Não Fazer',
    'Ação de Rescisão Contratual',
    'Ação Declaratória',
    'Ação Revisional de Contrato',
    'Ação de Prestação de Contas',
    'Ação de Consignação em Pagamento',
    'Ação de Exibição de Documentos',
    'Tutela de Urgência (Antecipada)',

    # Consumidor
    'Ação de Indenização - Relação de Consumo',
    'Ação Revisional - Relação de Consumo',

    # Família / Sucessões
    'Ação de Alimentos',
    'Revisional de Alimentos',
    'Exoneração de Alimentos',
    'Guarda',
    'Regulamentação de Visitas',
    'Divórcio Consensual',
    'Divórcio Litigioso',
    'Reconhecimento e Dissolução de União Estável',
    'Inventário',
    'Arrolamento',

    # Imobiliário / Locação
    'Ação de Despejo',
    'Ação de Cobrança de Aluguéis',
    'Ação Renovatória de Locação',

    # Tributário
    'Execução Fiscal',
    'Embargos à Execução',
    'Mandado de Segurança',

    # Trabalhista
    'Reclamação Trabalhista',

    # Penal
    'Habeas Corpus',

    # Empresarial / Societário
    'Ação de Dissolução Parcial de Sociedade',
    'Ação de Apuração de Haveres',
]


def seed_titulos(apps, schema_editor):
    CaseTituloOption = apps.get_model('cases', 'CaseTituloOption')

    # Em migrations, não dependa do user model real; deixa created_by nulo.
    for label in TITULOS_SEED:
        cleaned = ' '.join(str(label or '').split()).strip()
        if not cleaned:
            continue

        key = _normalize_key(cleaned)
        if not key:
            continue

        obj, created = CaseTituloOption.objects.get_or_create(
            key=key,
            defaults={
                'label': cleaned,
                'is_active': True,
                'created_by': None,
            },
        )
        if not created:
            # Mantém o label já existente; só garante que está ativo.
            if not obj.is_active:
                obj.is_active = True
                obj.save(update_fields=['is_active'])


def unseed_titulos(apps, schema_editor):
    CaseTituloOption = apps.get_model('cases', 'CaseTituloOption')
    keys = [_normalize_key(' '.join(str(v or '').split()).strip()) for v in TITULOS_SEED]
    keys = [k for k in keys if k]
    if keys:
        CaseTituloOption.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_casetitulooption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_titulos, reverse_code=unseed_titulos),
    ]
