# Generated by Django 4.2.28 on 2026-03-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_seed_casetitulooption'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_principal',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, indica que este processo é derivado e aponta para o processo principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_derivados', to='cases.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='vinculo_tipo',
            field=models.CharField(blank=True, choices=[('DERIVADO', 'Derivado'), ('APENSO', 'Apenso'), ('INCIDENTE', 'Incidente'), ('CUMPRIMENTO', 'Cumprimento de Sentença'), ('RECURSO', 'Recurso'), ('OUTRO', 'Outro')], default='', help_text='Tipo do vínculo com o processo principal (somente quando case_principal está preenchido).', max_length=20),
        ),
    ]
