# Generated by Django 4.2.28 on 2026-03-23 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0019_case_case_principal_case_vinculo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('DERIVADO', 'Derivado'), ('APENSO', 'Apenso'), ('INCIDENTE', 'Incidente'), ('CUMPRIMENTO', 'Cumprimento de Sentença'), ('RECURSO', 'Recurso'), ('OUTRO', 'Outro')], help_text='Tipo do vínculo', max_length=20)),
                ('link_date', models.DateField(blank=True, help_text='Data do vínculo (quando aplicável)', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Observação/justificativa do vínculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_links', to=settings.AUTH_USER_MODEL)),
                ('from_case', models.ForeignKey(help_text='Processo de origem do vínculo', on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='cases.case')),
                ('to_case', models.ForeignKey(help_text='Processo de destino do vínculo', on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='cases.case')),
            ],
            options={
                'verbose_name': 'Vínculo entre Processos',
                'verbose_name_plural': 'Vínculos entre Processos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_case', 'to_case'], name='cases_casel_from_ca_1dc396_idx'), models.Index(fields=['link_type'], name='cases_casel_link_ty_f667c4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='caselink',
            constraint=models.CheckConstraint(check=models.Q(('from_case', models.F('to_case')), _negated=True), name='case_link_no_self_link'),
        ),
        migrations.AddConstraint(
            model_name='caselink',
            constraint=models.UniqueConstraint(fields=('from_case', 'to_case', 'link_type'), name='unique_case_link_per_type'),
        ),
    ]
