# Generated by Django 4.2.28 on 2026-03-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0022_merge_comarca_into_vara_and_remove_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseparty',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente/Representado'), ('AUTOR', 'Autor'), ('REU', 'Réu'), ('TESTEMUNHA', 'Testemunha'), ('PERITO', 'Perito'), ('TERCEIRO', 'Terceiro Interessado')], default='CLIENTE', help_text='Papel da parte no processo', max_length=100),
        ),
        migrations.CreateModel(
            name='CasePartyRoleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto exibido na lista', max_length=100)),
                ('key', models.CharField(db_index=True, help_text='Chave normalizada (sem acento, minúscula, espaços colapsados) para deduplicação', max_length=140, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_party_role_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção de Papel da Parte',
                'verbose_name_plural': 'Opções de Papel da Parte',
                'ordering': ['label'],
            },
        ),
    ]
