# Generated by Django 4.2.28 on 2026-03-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_owner_contact_contacts_co_owner_i_1287e0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0023_alter_caseparty_role_casepartyroleoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRepresentationTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto exibido na lista', max_length=100)),
                ('key', models.CharField(db_index=True, help_text='Chave normalizada (sem acento, minúscula, espaços colapsados) para deduplicação', max_length=140, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_representation_type_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção de Tipo de Representação',
                'verbose_name_plural': 'Opções de Tipo de Representação',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CaseRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation_type', models.CharField(blank=True, default='', help_text='Tipo de representação (texto livre; pode vir da lista de opções)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_representations', to=settings.AUTH_USER_MODEL)),
                ('representative_contact', models.ForeignKey(help_text='Contato representante/responsável no contexto deste processo', on_delete=django.db.models.deletion.CASCADE, related_name='case_representations_as_representative', to='contacts.contact')),
                ('represented_contact', models.ForeignKey(help_text='Contato representado (normalmente o cliente do processo)', on_delete=django.db.models.deletion.CASCADE, related_name='case_representations_as_represented', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Representação no Processo',
                'verbose_name_plural': 'Representações no Processo',
            },
        ),
        migrations.AddConstraint(
            model_name='caserepresentation',
            constraint=models.UniqueConstraint(fields=('case', 'represented_contact'), name='unique_representation_per_case_and_represented_contact'),
        ),
        migrations.AddConstraint(
            model_name='caserepresentation',
            constraint=models.CheckConstraint(check=models.Q(('represented_contact', models.F('representative_contact')), _negated=True), name='case_representation_no_self_representation'),
        ),
    ]
