# Generated by Django 4.2.28 on 2026-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_sync_case_select_options_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='hora_vencimento',
            field=models.TimeField(blank=True, help_text='Hora limite da tarefa (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='caseparty',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('AUTOR', 'Autor'), ('REU', 'Réu'), ('TESTEMUNHA', 'Testemunha'), ('PERITO', 'Perito'), ('TERCEIRO', 'Terceiro Interessado')], default='CLIENTE', help_text='Papel da parte no processo', max_length=100),
        ),
    ]
