# Generated by Django 4.2.28 on 2026-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_casevinculotipooption_delete_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='classificacao',
            field=models.CharField(choices=[('NEUTRO', 'Neutro'), ('PRINCIPAL', 'Principal')], db_index=True, default='NEUTRO', help_text='Classificação do processo (quando não há case_principal).', max_length=20),
        ),
    ]
