"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lê do arquivo .env (backend/.env)
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'django_filters',
    'corsheaders',
    
    # Apps do projeto
    'apps.contacts',
    'apps.publications',
    'apps.notifications',
    'apps.cases',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'storage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite dev server (padrão)
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': None,  # Sem paginação - carregar todos os contatos
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# Configurações de OAB para publicações
OAB_NUMBER = config('OAB_NUMBER', default='507553')
ADVOGADA_NOME = config('ADVOGADA_NOME', default='Vitoria Rocha de Morais')
# Nota: O sistema aplica filtros inteligentes:
# 1. POSITIVO: Garante menção à OAB/nome no texto (evita falsos positivos)
# 2. NEGATIVO: Exclui publicações de outras advogadas (ex: LÚCIA VITÓRIA - OAB 407729)
# Ajuste em services/pje_comunica.py → EXCLUDED_LAWYERS

# ===== SISTEMA DE CONFIGURAÇÕES =====
# Configurações centralizadas para controlar comportamento do sistema
# Editáveis via API /api/system-settings
LEGAL_SYSTEM_SETTINGS = {
    # ===== PUBLICAÇÕES =====
    'AUTO_LOAD_PUBLICATIONS_ON_CASE': True,
    'AUTO_LOAD_PUBLICATIONS_ON_CONTACTS': True,
    'AUTO_CREATE_MOVEMENT_ON_PUBLICATION_INTEGRATION': False,
    'PUBLICATION_CACHE_DURATION': 300,  # em segundos, 0 = sem cache
    
    # ===== MOVIMENTAÇÕES =====
    'AUTO_LOAD_MOVEMENTS_ON_CASE': True,
    'AUTO_CHECK_DEADLINES': True,
    'DEADLINE_NOTIFICATION_DAYS': 7,
    'DEADLINE_NOTIFICATION_BEFORE_DAYS': 3,

    # ===== TAREFAS DO PROCESSO =====
    'AUTO_LOAD_TASKS_ON_CASE': True,
    'TASK_NORMAL_DAYS': 15,
    'TASK_URGENT_DAYS': 7,
    'TASK_URGENTISSIMO_DAYS': 3,
    'TASK_NORMAL_COLOR': '#10b981',
    'TASK_URGENT_COLOR': '#f59e0b',
    'TASK_URGENTISSIMO_COLOR': '#dc2626',
    
    # ===== PARTES =====
    'AUTO_LOAD_PARTIES_ON_CASE': True,
    'ALLOW_MULTIPLE_ROLES_PER_CONTACT': True,  # Um contato pode ter vários papéis no caso
    
    # ===== PAGAMENTOS E DESPESAS =====
    'AUTO_LOAD_PAYMENTS_ON_CASE': True,
    'AUTO_LOAD_EXPENSES_ON_CASE': True,
    
    # ===== INTERFACE E UX =====
    'AUTO_LOAD_DOCUMENTS_ON_CASE': True,
    'ENABLE_SOFT_DELETE': True,  # Manter registros deletados no banco (não permanentemente apagá-los)
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_RESULTS_PER_SEARCH': 100,
    
    # ===== SISTEMA =====
    'ENVIRONMENT': config('ENVIRONMENT', default='development'),
    'DEBUG_MODE': DEBUG,
    'LOG_API_REQUESTS': config('LOG_API_REQUESTS', default=False, cast=bool),
}