"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
import dj_database_url
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lê do arquivo .env (backend/.env)
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

def _collect_local_ipv4_hosts() -> list[str]:
    hosts = {'localhost', '127.0.0.1'}
    try:
        hostname = socket.gethostname()
        if hostname:
            hosts.add(hostname)
            hosts.add(hostname.lower())
            hosts.add(hostname.upper())
    except Exception:
        pass

    # Includes all IPv4 addresses assigned to local interfaces.
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if ip:
                hosts.add(ip)  # type: ignore[arg-type]
    except Exception:
        pass

    return sorted(hosts)


ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
for local_host in _collect_local_ipv4_hosts():
    if local_host not in ALLOWED_HOSTS:  # type: ignore[operator]
        ALLOWED_HOSTS.append(local_host)  # type: ignore[union-attr]

# === Segurança de produção (ativadas quando DEBUG=False) ===
# Todas controladas via .env — sem código diferente entre dev e prod
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Rate limiting leve via WSGI (complementado pelo gunicorn/nginx)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'django_filters',
    'corsheaders',
    
    # Apps do projeto
    'apps.accounts',
    'apps.contacts',
    'apps.publications',
    'apps.notifications',
    'apps.cases',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Suporta SQLite (dev) e PostgreSQL (prod) via DATABASE_URL no .env
# Exemplos:
#   SQLite:     DATABASE_URL=sqlite:///db.sqlite3
#   PostgreSQL: DATABASE_URL=postgresql://user:pass@localhost:5432/legal_system

_DATABASE_URL = config('DATABASE_URL', default=f'sqlite:///{PROJECT_ROOT / "db.sqlite3"}')
DATABASES = {
    'default': dj_database_url.parse(_DATABASE_URL, conn_max_age=600)  # type: ignore[arg-type]
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'config.password_validators.StrongPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'storage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Em produção, defina via .env:
#   CORS_ALLOWED_ORIGINS=http://192.168.1.10:5173,http://meuescritorio.local
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)
for local_host in _collect_local_ipv4_hosts():
    local_origin = f'http://{local_host}:5173'
    if local_origin not in CORS_ALLOWED_ORIGINS:  # type: ignore[operator]
        CORS_ALLOWED_ORIGINS.append(local_origin)  # type: ignore[union-attr]
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': None,  # Sem paginação - carregar todos os contatos
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# ===== PUBLICAÇÕES / PJe Comunica =====
# Identidade padrão (fallback) para consultas quando usuário não tem perfil.
# Em produção, configure via .env ou (preferível) use o perfil do usuário.
OAB_NUMBER = config('OAB_NUMBER', default='')
ADVOGADA_NOME = config('ADVOGADA_NOME', default='')

# Integração com PJe Comunica
PJE_COMUNICA_API_URL = config('PJE_COMUNICA_API_URL', default='https://comunicaapi.pje.jus.br/api/v1/comunicacao')
PJE_COMUNICA_TIMEOUT_SECONDS = config('PJE_COMUNICA_TIMEOUT_SECONDS', default=15, cast=int)
PJE_COMUNICA_MAX_RETRIES = config('PJE_COMUNICA_MAX_RETRIES', default=2, cast=int)
PJE_COMUNICA_RETRY_BACKOFF_SECONDS = config(
    'PJE_COMUNICA_RETRY_BACKOFF_SECONDS',
    default='0.75,2.0',
    cast=Csv(),
)
PJE_COMUNICA_DEFAULT_TRIBUNAIS = config(
    'PJE_COMUNICA_DEFAULT_TRIBUNAIS',
    default='TJSP,TRF3,TRT2,TRT15,TJMG',
    cast=Csv(),
)

# Regras globais (fallback) para rejeitar publicações de advogados similares.
# Preferível configurar por usuário (UserProfile), mas esses valores servem como padrão.
PJE_COMUNICA_EXCLUDED_LAWYERS_OABS = config(
    'PJE_COMUNICA_EXCLUDED_LAWYERS_OABS',
    default='',
    cast=Csv(),
)
PJE_COMUNICA_EXCLUDED_LAWYERS_KEYWORDS = config(
    'PJE_COMUNICA_EXCLUDED_LAWYERS_KEYWORDS',
    default='',
    cast=Csv(),
)

# Limites operacionais (evitar spam/volume)
PUBLICATIONS_NOTIFICATION_MAX_PER_SEARCH = config(
    'PUBLICATIONS_NOTIFICATION_MAX_PER_SEARCH',
    default=5,
    cast=int,
)
DEFAULT_MASTER_USERNAME = config(
    'MASTER_USERNAME',
    default=config('DJANGO_SUPERUSER_USERNAME', default=config('SUPERUSER_USERNAME', default='master')),
)
DEFAULT_MASTER_EMAIL = config(
    'MASTER_EMAIL',
    default=config('DJANGO_SUPERUSER_EMAIL', default='master@local.invalid'),
)
DEFAULT_MASTER_PASSWORD = config(
    'MASTER_PASSWORD',
    default=config('DJANGO_SUPERUSER_PASSWORD', default=config('SENHA_SUPERUSER', default='AltereEstaSenha!123')),
)
DEFAULT_MASTER_FIRST_NAME = config('MASTER_FIRST_NAME', default='Master')
# Nota: O sistema aplica filtros inteligentes:
# 1. POSITIVO: Garante menção à OAB/nome no texto (evita falsos positivos)
# 2. NEGATIVO: Exclui publicações de terceiros com nome/OAB parecidos (via lista de exclusão)
# Ajuste em services/pje_comunica.py → EXCLUDED_LAWYERS

# ===== SISTEMA DE CONFIGURAÇÕES =====
# Configurações centralizadas para controlar comportamento do sistema
# Editáveis via API /api/system-settings
LEGAL_SYSTEM_SETTINGS = {
    # ===== PUBLICAÇÕES =====
    'AUTO_LOAD_PUBLICATIONS_ON_CASE': True,
    'AUTO_LOAD_PUBLICATIONS_ON_CONTACTS': True,
    'AUTO_CREATE_MOVEMENT_ON_PUBLICATION_INTEGRATION': True,
    'HIDE_PUBLICATIONS_TAB_WHEN_AUTO_SYNC': True,  # Oculta aba Publicações se auto-create movement estiver ativo
    'PUBLICATION_CACHE_DURATION': 300,  # em segundos, 0 = sem cache
    # Se False: publicações deletadas (lixeira) ficam bloqueadas e não são reimportadas em novas buscas.
    # Se True (padrão): ao deletar e buscar novamente o mesmo período, a publicação pode reaparecer.
    'PUBLICATIONS_ALLOW_REIMPORT_AFTER_DELETE': True,
    
    # ===== MOVIMENTAÇÕES =====
    'AUTO_LOAD_MOVEMENTS_ON_CASE': True,
    'AUTO_CHECK_DEADLINES': True,
    'DEADLINE_NOTIFICATION_DAYS': 7,
    'DEADLINE_NOTIFICATION_BEFORE_DAYS': 3,

    # ===== MONITORAMENTO (90+ dias sem movimentação) =====
    # Observação: o agendamento (rodar na hora certa) é feito via Task Scheduler/cron.
    'STALE_PROCESS_MONITOR_ENABLED': False,
    'STALE_PROCESS_MONITOR_TIME': '09:00',
    'STALE_PROCESS_DAYS_THRESHOLD': 90,

    # ===== TAREFAS DO PROCESSO =====
    'AUTO_LOAD_TASKS_ON_CASE': True,
    'TASK_NORMAL_DAYS': 15,
    'TASK_URGENT_DAYS': 7,
    'TASK_URGENTISSIMO_DAYS': 3,
    'TASK_NORMAL_COLOR': '#10b981',
    'TASK_URGENT_COLOR': '#f59e0b',
    'TASK_URGENTISSIMO_COLOR': '#dc2626',
    
    # ===== PARTES =====
    'AUTO_LOAD_PARTIES_ON_CASE': True,
    'ALLOW_MULTIPLE_ROLES_PER_CONTACT': True,  # Um contato pode ter vários papéis no caso
    
    # ===== PAGAMENTOS E DESPESAS =====
    'AUTO_LOAD_PAYMENTS_ON_CASE': True,
    'AUTO_LOAD_EXPENSES_ON_CASE': True,
    
    # ===== INTERFACE E UX =====
    'AUTO_LOAD_DOCUMENTS_ON_CASE': True,
    'ENABLE_SOFT_DELETE': True,  # Manter registros deletados no banco (não permanentemente apagá-los)
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_RESULTS_PER_SEARCH': 100,
    
    # ===== SISTEMA =====
    'ENVIRONMENT': config('ENVIRONMENT', default='development'),
    'DEBUG_MODE': DEBUG,
    'LOG_API_REQUESTS': config('LOG_API_REQUESTS', default=False, cast=bool),
}

JWT_ACCESS_TOKEN_HOURS = config('JWT_ACCESS_TOKEN_HOURS', default=8, cast=float)
JWT_REFRESH_TOKEN_HOURS = config('JWT_REFRESH_TOKEN_HOURS', default=168, cast=float)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=max(JWT_ACCESS_TOKEN_HOURS, 0.1)),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=max(JWT_REFRESH_TOKEN_HOURS, 1)),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}