#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Install Legal System on a Windows server machine.

.DESCRIPTION
    First-time setup script:
      1) Check prerequisites (Git, Python, Node.js)
      2) Clone/update repository
      3) Create Python virtual environment and install dependencies
      4) Create backend .env using detected local IP
      5) Run migrations + collectstatic
      6) Build frontend for production
      7) Register Windows services using NSSM
#>

param(
    [string]$InstallPath = "C:\dev\legal-system",
    [string]$RepoUrl = "https://github.com/EduFBasso/legal-system.git",
    [string]$Branch = "main"
)

$ErrorActionPreference = "Stop"

function Write-Step { param([string]$msg) Write-Host "`n== $msg" -ForegroundColor Cyan }
function Write-OK { param([string]$msg) Write-Host "  [OK]  $msg" -ForegroundColor Green }
function Write-Warn { param([string]$msg) Write-Host "  [!!]  $msg" -ForegroundColor Yellow }
function Write-Fail { param([string]$msg) Write-Host "`n  [ERR] $msg" -ForegroundColor Red; exit 1 }
function Write-Info { param([string]$msg) Write-Host "       $msg" -ForegroundColor Gray }

$venvPython = "$InstallPath\.venv\Scripts\python.exe"
$venvPip = "$InstallPath\.venv\Scripts\pip.exe"
$nssmPath = "$InstallPath\nssm-2.24\win64\nssm.exe"
$backendDir = "$InstallPath\backend"
$frontendDir = "$InstallPath\frontend"

Write-Host ""
Write-Host "=========================================================="
Write-Host "        LEGAL SYSTEM - WINDOWS SERVER INSTALLER"
Write-Host "=========================================================="

Write-Step "1/8 Check prerequisites"
$git = Get-Command git    -ErrorAction SilentlyContinue
$python = Get-Command python -ErrorAction SilentlyContinue
$pyLauncher = Get-Command py -ErrorAction SilentlyContinue
$node = Get-Command node   -ErrorAction SilentlyContinue
$npm = Get-Command npm    -ErrorAction SilentlyContinue

$pythonCmd = $null
if ($python) {
    try {
        $probe = (python --version 2>&1 | Out-String).Trim()
        if ($probe -match '^Python\s+3\.11(\.|$)') {
            $pythonCmd = 'python'
        }
    }
    catch {
        # ignore and fallback to py launcher
    }
}
if (-not $pythonCmd -and $pyLauncher) {
    try {
        $probe = (& py -3.11 --version 2>&1 | Out-String).Trim()
        if ($probe -match '^Python\s+3\.11(\.|$)') {
            $pythonCmd = 'py -3.11'
        }
    }
    catch {
        # keep null
    }
}

$missing = @()
if (-not $git) { $missing += "Git    -> https://git-scm.com/download/win" }
if (-not $pythonCmd) { $missing += "Python 3.11 -> https://www.python.org/downloads/release/python-3119/" }
if (-not $node) { $missing += "Node   -> https://nodejs.org/en (LTS)" }
if (-not $npm) { $missing += "npm    (installed together with Node.js)" }

if ($missing.Count -gt 0) {
    Write-Host ""
    Write-Host "Install required tools first:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    exit 1
}

if ($pythonCmd -eq 'python') {
    $pyVer = (python --version 2>&1) -replace "Python ", ""
}
else {
    $pyVer = (& py -3.11 --version 2>&1) -replace "Python ", ""
}
$nodeVer = (node --version 2>&1) -replace "v", ""
Write-OK "Python $pyVer | Node.js $nodeVer | Git ok"

Write-Step "2/8 Detect local IP"
$detectedIP = (
    Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.PrefixOrigin -in @('Dhcp', 'Manual') } |
    Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.*' } |
    Select-Object -First 1
).IPAddress

if (-not $detectedIP) {
    $detectedIP = "127.0.0.1"
    Write-Warn "Could not detect local IP. Using 127.0.0.1."
}
else {
    Write-OK "Detected IP: $detectedIP"
}
$hostName = $env:COMPUTERNAME

Write-Step "3/8 Repository"
if (Test-Path "$InstallPath\.git") {
    Write-OK "Repository already exists. Updating..."
    Set-Location $InstallPath
    git fetch origin
    git checkout $Branch
    git pull origin $Branch
}
else {
    Write-Info "Cloning repository..."
    git clone --branch $Branch $RepoUrl $InstallPath
    Write-OK "Clone completed"
}
Set-Location $InstallPath

Write-Step "4/8 Python environment"
if (-not (Test-Path "$InstallPath\.venv")) {
    Write-Info "Creating virtual environment..."
    if ($pythonCmd -eq 'python') {
        python -m venv "$InstallPath\.venv"
    }
    else {
        & py -3.11 -m venv "$InstallPath\.venv"
    }
}

Write-Info "Installing Python dependencies..."
& $venvPip install --upgrade pip --quiet
& $venvPip install -r "$backendDir\requirements.txt" --quiet
Write-OK "Python dependencies installed"

Write-Step "5/8 Configure backend .env"
$chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
$secretKey = -join ((1..60) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })

$envContent = @"
# Auto-generated by INSTALAR_SERVIDOR.ps1 on $(Get-Date -Format 'yyyy-MM-dd')
# Do not commit this file.

SECRET_KEY=$secretKey
DEBUG=False

ALLOWED_HOSTS=localhost,127.0.0.1,$detectedIP,$hostName
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://${detectedIP}:5173,http://${hostName}:5173

# SQLite default database (copy db.sqlite3 from old machine if needed)
# DATABASE_URL=sqlite:///db.sqlite3

OAB_NUMBER=507553
ADVOGADA_NOME=Vitoria Rocha de Morais
JWT_ACCESS_TOKEN_HOURS=8
JWT_REFRESH_TOKEN_HOURS=168
"@

$envPath = "$backendDir\.env"
if (Test-Path $envPath) {
    Write-Warn "backend/.env already exists. Keeping current file."
}
else {
    $envContent | Set-Content -Encoding ASCII $envPath
    Write-OK "backend/.env created"
}

Write-Step "6/8 Database setup"
Set-Location $backendDir
Write-Info "Running migrations..."
& $venvPython manage.py migrate --noinput
Write-OK "Migrations done"

Write-Info "Collecting static files..."
& $venvPython manage.py collectstatic --noinput 2>&1 | Out-Null
Write-OK "Static files collected"

Write-Info "Checking superuser..."
$createUser = & $venvPython manage.py shell -c @"
from django.contrib.auth import get_user_model
User = get_user_model()
print('exists' if User.objects.filter(is_superuser=True).exists() else 'missing')
"@
if ($createUser.Trim() -eq 'missing') {
    Write-Warn "No superuser found. Create one later with:"
    Write-Info "  cd $backendDir"
    Write-Info "  $venvPython manage.py createsuperuser"
}
else {
    Write-OK "Superuser already exists"
}

Write-Host ""
Write-Host "IMPORTANT: If you have old data, copy db.sqlite3 from old machine:"
Write-Host "  C:\dev\legal-system\backend\db.sqlite3"
Write-Host "to the same path on this machine."

Write-Step "7/8 Frontend production build"
Set-Location $frontendDir
$envLocalPath = "$frontendDir\.env.local"
if (Test-Path $envLocalPath) {
    Write-Warn "frontend/.env.local already exists. Keeping current file."
}
else {
    @"
VITE_API_URL=http://${detectedIP}:8000/api
"@ | Set-Content -Encoding ASCII $envLocalPath
    Write-OK "frontend/.env.local created"
}

Write-Info "npm install..."
npm install --silent
Write-OK "npm install done"

Write-Info "npm run build..."
npm run build
Write-OK "Frontend build generated"

Write-Step "8/8 Register Windows services (NSSM)"
Set-Location $InstallPath
if (-not (Test-Path $nssmPath)) {
    Write-Warn "NSSM not found at: $nssmPath"
    Write-Warn "Services were not registered."
    Write-Info "Run manually: infra\\backend_prod.cmd and infra\\frontend_prod.cmd"
}
else {
    $backendCmd = "$InstallPath\infra\backend_prod.cmd"
    $frontendCmd = "$InstallPath\infra\frontend_prod.cmd"

    $svcBack = Get-Service -Name "LegalSystem-Backend" -ErrorAction SilentlyContinue
    if ($svcBack) {
        Stop-Service "LegalSystem-Backend" -Force -ErrorAction SilentlyContinue
        & $nssmPath set LegalSystem-Backend Application "C:\Windows\System32\cmd.exe"
        & $nssmPath set LegalSystem-Backend AppParameters "/c `"$backendCmd`""
    }
    else {
        & $nssmPath install LegalSystem-Backend "C:\Windows\System32\cmd.exe" "/c `"$backendCmd`""
    }
    & $nssmPath set LegalSystem-Backend AppDirectory $backendDir
    & $nssmPath set LegalSystem-Backend DisplayName "Legal System - Backend (Waitress)"
    & $nssmPath set LegalSystem-Backend Description "Django backend"
    & $nssmPath set LegalSystem-Backend Start SERVICE_AUTO_START
    Write-OK "LegalSystem-Backend configured"

    $svcFront = Get-Service -Name "LegalSystem-Frontend" -ErrorAction SilentlyContinue
    if ($svcFront) {
        Stop-Service "LegalSystem-Frontend" -Force -ErrorAction SilentlyContinue
        & $nssmPath set LegalSystem-Frontend Application "C:\Windows\System32\cmd.exe"
        & $nssmPath set LegalSystem-Frontend AppParameters "/c `"$frontendCmd`""
    }
    else {
        & $nssmPath install LegalSystem-Frontend "C:\Windows\System32\cmd.exe" "/c `"$frontendCmd`""
    }
    & $nssmPath set LegalSystem-Frontend AppDirectory $frontendDir
    & $nssmPath set LegalSystem-Frontend DisplayName "Legal System - Frontend (Vite Preview)"
    & $nssmPath set LegalSystem-Frontend Description "React frontend"
    & $nssmPath set LegalSystem-Frontend Start SERVICE_AUTO_START
    Write-OK "LegalSystem-Frontend configured"

    Write-Info "Starting services..."
    Start-Service "LegalSystem-Backend"
    Start-Sleep -Seconds 3
    Start-Service "LegalSystem-Frontend"
    Start-Sleep -Seconds 4

    $back = (Get-Service "LegalSystem-Backend").Status
    $front = (Get-Service "LegalSystem-Frontend").Status
    Write-OK "Backend: $back | Frontend: $front"
}

Set-Location $InstallPath
Write-Host ""
Write-Host "=========================================================="
Write-Host "                   INSTALLATION COMPLETED"
Write-Host "=========================================================="
Write-Host "Local URL : http://localhost:5173"
Write-Host "LAN URL   : http://${detectedIP}:5173"
Write-Host "API URL   : http://${detectedIP}:8000/api/"
Write-Host ""
Write-Host "To update later, run as Administrator: .\ATUALIZAR.ps1"
Write-Host ""
