# Generated by Django 4.2.28 on 2026-03-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', 'read'], name='notificatio_owner_i_568676_idx'),
        ),
    ]
