# Generated by Django 4.2.28 on 2026-03-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('notifications', '0002_notification_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização (tenant) desta notificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='organizations.organization', verbose_name='Organização'),
        ),
    ]
