# Generated by Django 4.2.28 on 2026-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('OPPOSING', 'Parte Contrária'), ('WITNESS', 'Testemunha'), ('LAWYER', 'Advogado Parceiro'), ('OTHER', 'Outro')], default='CLIENT', max_length=10, verbose_name='Tipo de Contato')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('name', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('document_number', models.CharField(blank=True, help_text='Formato: 000.000.000-00 ou 00.000.000/0000-00', max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, help_text='Sigla: SP, RJ, MG, etc.', max_length=2, null=True, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='contacts_co_name_6f3a2a_idx'), models.Index(fields=['contact_type', 'is_active'], name='contacts_co_contact_8c0a97_idx')],
            },
        ),
    ]
