# Generated by Django 4.2.28 on 2026-02-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_contact_8c0a97_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx'),
        ),
    ]
