# Generated by Django 4.2.28 on 2026-02-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do contato - 40x40px no card, 200x200px no modal', null=True, upload_to='contacts/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
