# Generated by Django 4.2.28 on 2026-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_photo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='trading_name',
            field=models.CharField(blank=True, help_text='Nome fantasia da empresa (diferente da razão social)', max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
