# Generated by Django 4.2.28 on 2026-02-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_trading_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_contact_d678b6_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
    ]
