# Generated by Django 4.2.28 on 2026-03-27 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_owner_contact_contacts_co_owner_i_1287e0_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título curto da tarefa', max_length=255)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição detalhada da tarefa')),
                ('urgencia', models.CharField(choices=[('NORMAL', 'Prazo Normal'), ('URGENTE', 'Prazo Urgente'), ('URGENTISSIMO', 'Prazo Urgentíssimo')], db_index=True, default='NORMAL', help_text='Nível de urgência da tarefa', max_length=20)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, help_text='Data limite da tarefa', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', help_text='Status de execução da tarefa', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, help_text='Quando a tarefa foi concluída', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(help_text='Contato relacionado à tarefa', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Tarefa do Contato',
                'verbose_name_plural': 'Tarefas do Contato',
                'ordering': ['data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['contact', 'status'], name='contacts_co_contact_748d2b_idx'), models.Index(fields=['urgencia', 'data_vencimento'], name='contacts_co_urgenci_42e989_idx')],
            },
        ),
    ]
