# Generated by Django 4.2.28 on 2026-03-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('contacts', '0006_contact_owner_contact_contacts_co_owner_i_1287e0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização (tenant) deste contato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='organizations.organization'),
        ),
    ]
