# Generated by ChatGPT on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contacttask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttask',
            options={
                'ordering': ['data_vencimento', 'hora_vencimento', '-created_at'],
                'verbose_name': 'Tarefa do Contato',
                'verbose_name_plural': 'Tarefas do Contato',
            },
        ),
        migrations.AddField(
            model_name='contacttask',
            name='hora_vencimento',
            field=models.TimeField(blank=True, help_text='Hora limite da tarefa (opcional)', null=True),
        ),
    ]
