# Generated by Django 4.2.28 on 2026-03-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MASTER', 'Master (Dono do Escritório)'), ('ADVOGADO', 'Advogado'), ('ESTAGIARIO', 'Estagiário')], default='ADVOGADO', max_length=20)),
                ('full_name_oab', models.CharField(blank=True, default='', help_text='Nome completo exatamente como deve ser usado na busca de publicações', max_length=200)),
                ('oab_number', models.CharField(blank=True, default='', help_text='Número da OAB usado para consulta de publicações', max_length=30)),
                ('monitored_tribunais', models.JSONField(blank=True, default=list, help_text='Lista de tribunais monitorados para buscas automáticas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_e16858_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_993040_idx')],
            },
        ),
    ]
