# Generated by Django 4.2.28 on 2026-03-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização (tenant) deste usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organization'),
        ),
    ]
