# Generated by Django 4.2.28 on 2026-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tribunais', models.JSONField(help_text='Lista de tribunais consultados')),
                ('total_publicacoes', models.IntegerField(default=0)),
                ('total_novas', models.IntegerField(default=0, help_text='Publicações que não existiam no banco')),
                ('search_params', models.JSONField(blank=True, default=dict, help_text='Parâmetros completos da busca')),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Tempo de execução da busca em segundos', null=True)),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Histórico de Buscas',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.BigIntegerField(db_index=True, unique=True)),
                ('numero_processo', models.CharField(blank=True, db_index=True, help_text='Número CNJ do processo', max_length=50, null=True)),
                ('tribunal', models.CharField(db_index=True, help_text='Ex: TJSP, TRF3, TRT2', max_length=10)),
                ('tipo_comunicacao', models.CharField(help_text='Ex: Intimação, Despacho, Citação', max_length=100)),
                ('data_disponibilizacao', models.DateField(db_index=True, help_text='Data de publicação no DJE')),
                ('orgao', models.CharField(blank=True, help_text='Órgão/Vara responsável', max_length=500)),
                ('meio', models.CharField(blank=True, help_text='Meio de comunicação (D=Digital, F=Físico)', max_length=10)),
                ('texto_resumo', models.TextField(help_text='Primeiros 500 caracteres', max_length=500)),
                ('texto_completo', models.TextField(help_text='Texto integral da publicação')),
                ('link_oficial', models.CharField(blank=True, help_text='URL para consulta no site do tribunal', max_length=500, null=True)),
                ('hash_pub', models.CharField(blank=True, help_text='Hash da publicação (quando disponível)', max_length=100, null=True)),
                ('search_metadata', models.JSONField(blank=True, default=dict, help_text='Dados da busca que encontrou esta publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quando foi salva no banco local')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_disponibilizacao', '-created_at'],
                'indexes': [models.Index(fields=['tribunal', '-data_disponibilizacao'], name='publication_tribuna_bff94d_idx'), models.Index(fields=['numero_processo'], name='publication_numero__a6bcef_idx'), models.Index(fields=['-created_at'], name='publication_created_b49296_idx')],
            },
        ),
    ]
