# Generated by Django 4.2.28 on 2026-02-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Se True, publicação foi excluída (soft delete)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da exclusão', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', help_text='Motivo da exclusão (ex: Exclusão manual pela advogada)', max_length=255),
        ),
    ]
