# Generated by Django 4.2.28 on 2026-02-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_observations_financial_block_a_and_more'),
        ('publications', '0002_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='case',
            field=models.ForeignKey(blank=True, db_index=True, help_text='Caso ao qual esta publicação está vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='publication',
            name='integration_status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Integração'), ('INTEGRATED', 'Integrada ao Caso'), ('IGNORED', 'Ignorada pela Advogada')], db_index=True, default='PENDING', help_text='Status da integração com o sistema', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='integration_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Última tentativa de integração automática', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='integration_notes',
            field=models.TextField(blank=True, default='', help_text='Observações sobre a integração (ex: Processo não cadastrado)'),
        ),
    ]
