# Generated by Django 4.2.28 on 2026-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_add_integration_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['integration_status', 'deleted'], name='publication_integra_59e9ce_idx'),
        ),
    ]
