# Generated by Django 4.2.28 on 2026-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_publication_integra_59e9ce_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publication',
            name='publication_integra_59e9ce_idx',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deleted_reason',
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['integration_status'], name='publication_integra_aec56e_idx'),
        ),
    ]
