# Generated by Django 4.2.28 on 2026-03-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0005_remove_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsável pelo escopo desta publicação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável por esta busca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id_api',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['owner', 'integration_status'], name='publication_owner_i_965f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['owner', '-data_disponibilizacao'], name='publication_owner_i_5bb61b_idx'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('owner', 'id_api'), name='unique_publication_id_api_per_owner'),
        ),
    ]
