# Generated by Django 4.2.28 on 2026-03-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0006_publication_owner_searchhistory_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDeletionTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.BigIntegerField(db_index=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tombstone de Publicação',
                'verbose_name_plural': 'Tombstones de Publicações',
            },
        ),
        migrations.AddConstraint(
            model_name='publicationdeletiontombstone',
            constraint=models.UniqueConstraint(fields=('owner', 'id_api'), name='unique_deleted_publication_id_api_per_owner'),
        ),
    ]
